# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepcache.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65\x65pcache.proto\x12\x03rpc\"~\n\tDCRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.rpc.OpType\x12\x0e\n\x06imgidx\x18\x03 \x01(\x03\x12\x13\n\x0bkvlist_json\x18\x04 \x01(\t\x12\x10\n\x08imgidx_t\x18\x05 \x01(\t\x12\x13\n\x0b\x66ull_access\x18\x06 \x01(\x08\"\x93\x01\n\x07\x44\x43Reply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0b\n\x03len\x18\x03 \x01(\x03\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\x0e\n\x06\x63lsidx\x18\x05 \x01(\x03\x12\x0e\n\x06imgidx\x18\x06 \x01(\x03\x12\x12\n\ncache_size\x18\x07 \x01(\x03\x12\x10\n\x08nsamples\x18\x08 \x01(\x03\x12\x0e\n\x06is_hit\x18\t \x01(\x08*z\n\x06OpType\x12\x12\n\x0eget_cache_info\x10\x00\x12\x11\n\rreadimg_byidx\x10\x01\x12\x16\n\x12update_ivpersample\x10\x02\x12\x13\n\x0freadimg_byidx_t\x10\x03\x12\x1c\n\x18refresh_server_ivpsample\x10\x04\x32\x36\n\x08Operator\x12*\n\x08\x44\x43Submit\x12\x0e.rpc.DCRequest\x1a\x0c.rpc.DCReply\"\x00\x42\nZ\x08./;cacheb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deepcache_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;cache'
  _OPTYPE._serialized_start=302
  _OPTYPE._serialized_end=424
  _DCREQUEST._serialized_start=24
  _DCREQUEST._serialized_end=150
  _DCREPLY._serialized_start=153
  _DCREPLY._serialized_end=300
  _OPERATOR._serialized_start=426
  _OPERATOR._serialized_end=480
# @@protoc_insertion_point(module_scope)
